extends Node

@export var story = [
	
	["Genres Chapter 1"],
	[
		"Acción / Shōnen de batallas Prota: Tsundere × Yandere × Genki ➤ Tres chicas luchan contra una organización hostil en un torneo urbano. La tsundere debe liderar aunque lo niegue.",
		"Terror psicológico / Sobrenatural Prota: Yandere × Dandere × Hinedere ➤ En una mansión encantada, la yandere comienza a sospechar que solo ella ve la verdad. ¿Paranoia o realidad?",
		"Ciencia ficción / Cyberpunk Prota: Kuudere × Kamidere × Bokodere ➤ Hackers en una ciudad futurista: la kuudere controla drones, mientras la kamidere quiere dominar la red.",
		"Aventura / Fantasía épica Prota: Deredere × Dandere × Sadodere ➤ Buscan reliquias mágicas. La deredere trata de mantener la paz entre sus opuestas compañeras.",
		"Mecha / Guerra de robots Prota: Kamidere × Kuudere × Undere ➤ Pilota el robot supremo, pero las otras dos tienen datos clave... y secretos que pueden cambiar la guerra.",
		"Misterio / Detective Prota: Dandere × Himedere × Yandere ➤ Una silenciosa genio del misterio investiga un asesinato escolar con ayuda (o estorbo) de dos personalidades intensas.",
		"Survival / Battle Royale Prota: Himedere × Bokodere × Tsundere ➤ Una princesa atrapada en un juego de muerte. ¿Se aliará o sacrificará a las otras dos?",
		"Deportes / Fútbol sobrenatural Prota: Genki × Kuudere × Deredere ➤ Un equipo disparejo intenta ganar un torneo donde los balones queman y el campo cambia cada 10 minutos.",
		"Simulación social / Vida diaria Prota: Bokodere × Deredere × Kamidere ➤ En un simulador de escuela, deben cumplir eventos sociales para no ser eliminadas del programa.",
		"Comedia absurda / Parodia de anime Prota: Mayadere × Genki × Hinedere ➤ Un anime que parodia a todos los géneros, con una ex-villana tratando de actuar “normal”.",
		"Post-apocalíptico / Supervivencia Prota: Shundere × Tsundere × Kuudere ➤ Una sobreviviente melancólica lidera un grupo entre ruinas y bestias mutantes.",
		"Historias de guerra / Tácticas militares Prota: Kuudere × Kamidere × Undere ➤ General fría que debe organizar tropas. Las decisiones emocionales pueden causar muertes… o victorias.",
		"Fantasía oscura / RPG de mazmorras Prota: Yottadere × Dandere × Sadodere ➤ Borracha de poder y maná, debe controlar sus impulsos mágicos para no destruir su propio equipo.",
		"Ciberterrorismo / Estrategia digital Prota: Hinedere × Deredere × Bokodere ➤ Sarcástica y antisocial, lidera una célula de contra-hackers que infiltra sistemas corporativos.",
		"Viajes temporales / Ciencia ficción Prota: Dandere × Kamidere × Genki ➤ Saltan entre líneas temporales tratando de evitar un desastre. ¿Quién tiene la memoria del futuro?",
		"Zombis / Horror de supervivencia Prota: Bokodere × Yandere × Tsundere ➤ La más débil del grupo debe aprender a pelear… mientras su “protección” se vuelve más peligrosa que los zombis.",
		"Mitología japonesa / Shinto / Folklore Prota: Kamidere × Dandere × Himedere ➤ Diosa encarnada lucha contra espíritus oscuros. ¿Puede confiar en sus “sacerdotisas”?",
		"Isekai de comedia Prota: Deredere × Mayadere × Kuudere ➤ Una chica adorable reencarna en un slime… y ahora lidera a una ex-villana y a una fría heroína.",
		"Carreras / Competencia futurista Prota: Genki × Tsundere × Bokodere ➤ Compiten en carreras ilegales sobre motos flotantes. El riesgo está en la velocidad… y en las emociones.",
		"Juego de estrategia / Estilo Fire Emblem Prota: Kuudere × Yandere × Deredere ➤ Una comandante debe elegir qué unidades sacrificar. Las emociones ponen en peligro su objetividad.",
		"Terror lovecraftiano / Horror cósmico Prota: Undere × Hinedere × Sadodere ➤ En un pueblo maldito, la que siempre dice “sí” empieza a oír cosas que ninguna otra puede oír.",
		"Escape room / Puzzle survival Prota: Kitikudere × Deredere × Genki ➤ Solo una puede escapar. ¿Alguien confiaría en la que disfruta verlas fallar?",
		"Fantasía escolar / Magia diaria Prota: Kekkondere × Kuudere × Bokodere ➤ Sueña con un “hogar mágico perfecto”, pero la escuela está a punto de ser destruida.",
		"MOBA / Juego competitivo online Prota: Goudere × Tsundere × Kamidere ➤ Ella lo hace todo por su equipo... hasta que empieza a cuestionar si ellas merecen su lealtad.",
	],
	["Chapter 1 default relationships"],
	[
		"Tsundere (prota) × Yandere × Dandere ➤ Un triángulo tenso: ella no sabe expresar su amor, pero es atrapada entre una obsesiva y una silenciosa.",
		"Yandere × Kuudere × Deredere ➤ Cree que el amor es suyo y de nadie más, pero una fría kuudere y una alegre deredere se interponen.",
		"Dandere × Genki × Kamidere ➤ Una chica callada solo quiere paz, pero una energética y una mandona desatan el caos.",
		"Kuudere × Himedere × Bokodere ➤ Ella parece indiferente, pero internamente se derrite con la princesa orgullosa y la tímida violenta.",
		"Deredere × Tsundere × Yandere ➤ Su dulzura puede unirlas… o provocar una batalla por su amor.",
		"Kamidere × Kuudere × Yandere ➤ Se cree una diosa, pero estas dos rivales la ponen a prueba: una con lógica, otra con locura.",
		"Himedere × Tsundere × Dandere ➤ Quiere que la traten como realeza, pero ¿puede gobernar sus sentimientos entre una torpe orgullosa y una silenciosa?",
		"Undere × Deredere × Kuudere ➤ Siempre dice “sí” a todo… hasta que el corazón le exige decidir por sí misma.",
		"Mayadere × Yandere × Tsundere ➤ Una ex-villana en rehabilitación se enamora de dos chicas peligrosamente intensas.",
		"Bokodere × Dandere × Kamidere ➤ Quiere amar, pero se asusta. ¿Podrá abrirse ante una silenciosa tierna y una que exige adoración?",
		"Shundere × Deredere × Genki ➤ Sufre tristeza crónica. Dos chicas le muestran caminos opuestos: la alegría suave o el torbellino de energía.",
		"Genki × Tsundere × Kuudere ➤ Extrovertida hasta el cansancio, intenta sacar sonrisas a una pareja casi imposible.",
		"Yottadere (borracha o ebria de amor) × Kuudere × Dandere ➤ Su amor es embriagante... literalmente. ¿Quién soportará su intensidad?",
		"Darudere (perezosa) × Himedere × Deredere ➤ Solo quiere dormir, pero las otras dos no la dejarán en paz hasta que sienta algo.",
		"Hinedere (cínica) × Bokodere × Yandere ➤ Una sarcástica sin fe en el amor, atrapada con una tímida que la ama… y una psicópata que la necesita.",
		"Oujidere × Kamidere × Kuudere ➤ Un príncipe narcisista (sí, chica), conoce a su “reina” y su “sirvienta” de hielo. ¿Triángulo o guerra?",
		"Sadodere × Dandere × Deredere ➤ Le encanta provocar… pero ¿qué pasa cuando la ternura le desarma?",
		"Bakadere × Tsundere × Yandere ➤ Una tonta adorable que enamora sin saberlo… de forma muy peligrosa.",
		"Megadere (enamorada intensa) × Kuudere × Bokodere ➤ Vive por el amor… aunque no lo reciba de vuelta (o sí, pero a su manera).",
		"Kekkondere (quiere casarse de inmediato) × Kamidere × Dandere ➤ Su lema: “¡Matrimonio ya!” ¿Aceptarán su propuesta?",
		"Kitikudere (cruel con los que ama) × Deredere × Kuudere ➤ Solo sabe herir, pero alguien dulce y alguien fría le muestran otro camino.",
		"Yottadere × Genki × Hinedere ➤ Su obsesión con la diversión desata un caos emocional.",
		"Nemuidere (dormilona) × Deredere × Bokodere ➤ Solo despierta por amor… si alguien logra que abra los ojos.",
		"Goudere (excesivamente servicial) × Kamidere × Tsundere ➤ Haría cualquier cosa por complacer… pero ¿a quién de las dos?",
	]
	
	
]
