extends Node

@export var offset = [
	3, 19, 6, 7, 1, 12, 15, 7, 6, 8, 23, 5, 10, 10, 1, 15, 8, 9, 13, 17, 15, 16, 5, 0, 21, 19, 19, 17, 1, 23, 13, 22, 16, 20, 23, 18, 1, 2, 17, 22, 2, 12, 1, 2, 20, 2, 20, 3, 20, 9, 4, 16
]

func GetText(question, family, girl):
	var mytext = %Variables.questions[question]
	var id = (offset[question] + %Family.selected + girl + offset[-question]) % 24
	match(mytext):
		"Motivaciones": return %Variables.motivaciones[id]
		"Miedos": return %Variables.miedos[id]
		"Deseos y necesidades": return %Variables.deseos[id]
		"Creencias y valores": return %Variables.creencias[id]
		"Personalidad": return %Variables.personality_names[id] + "    :     " + %Variables.personality_definitions[id]
		"Pasado o historia personal": return %Variables.past_names[id] + "    :     " + %Variables.past_definitions[id]
		"Reacciones al heroe": return %Variables.hero_reactions[id] + "    :     " + %Variables.hero_reactions_definitions[id]
		"Celos": return %Variables.celos[id]
		"Perder la Virginidad": return %Variables.losing_virginity[id]
		"Estar en un trio": return %Variables.threesome[id]
		"Reacion al harem": return %Variables.harem_orgy[id]
		"Reaccion a compartir el heroe": return %Variables.sfw_ffm[id]
		"Reaccion violacion": return %Variables.rape_reactions[id]
		"Kabe don": return %Variables.kabe_don[id]
		"Enema": return %Variables.enema[id]
		"Fecaleptomia": return %Variables.fecaleptomia[id]
		"Histeria" : return %Variables.histeria[id]
		"Mid Histeria": return %Variables.mid_histeria[id]
		"Mirando el Consolador del prota": return %Variables.consolator_watch[id]
		"Penetracion": return %Variables.penetration[id]
		"Anal Histeria": return %Variables.anal_histeria[id]
		"Anal Histeria 2": return %Variables.anal_histeria2[id]
		"Orgasmo": return %Variables.orgasm[id]
		"Axilas olidas": return %Variables.armpits_sniffed[id]
		"Abrazo Sorpresa": return %Variables.sudden_hug[id]
		"Victoria" : return %Variables.victory[id]
		"Estar Asustada": return %Variables.scared[id]
		"Conflictos internos": return %Variables.inner_conflict[id]
		"Dilema moral": return %Variables.moral_dilemma[id]
		"Pasatiempos": return %Variables.hobbies[id]
		"Hobby vergonzoso": return %Variables.shameful_hobby[id]
		"Objeto mas Preciado": return %Variables.treasure_object[id]
		"Reaccion al ver un ternero mamar": return %Variables.calf_udder[id]
		"Ritual de lactancia": return %Variables.hero_suck[id]
		"Pensamientos intrusivos sobre el prota": return %Variables.intrusive_ideas_hero[id]
		"Pensamientos intrusivos": return %Variables.intrusive_ideas[id]
		"Auto Sabotaje con el Heroe": return %Variables.self_doubt_heroe[id]
		"Duda en sus habilidades": return %Variables.self_doubt_job[id]
		"Duda en sus trabajo jrpg": return %Variables.self_doubt_jrpg_job[id]
		"Usando el dinero del heroe": return %Variables.using_hero_money[id]
		"Opiniones entre ricos y pobres": return %Variables.rich_poor[id]
		"Moralidad": return %Variables.morality[id]
		"Embarazo": return %Variables.pregnancy[id]
		"Dere favorita": return %Variables.favorite_dere[id]
		"Porque son la mejor": return %Variables.self_favorite[id]
		"Objetivo dramático": return %Variables.dramatic_objective[id]
		"Arco principal": return %Variables.character_arc[id]
		"Arco tragico": return %Variables.tragic_arc[id]
		"Reaccion a sufrir dry hump": return %Variables.dry_hump[id]
		"Teabagging": return %Variables.teabagging[id]
		"Trata de blancas": return %Variables.human_trackficking[id]
		"Reacion ante un prostibulo": return %Variables.prostitution[id]
